<a href="https://colab.research.google.com/github/akaver/NLP2019/blob/master/Lab07_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook shows how to install Pytorch at Google Colab, and so some simple gradient computation using it.

Pytorch is available on Colab by default. If running on your own computer, you probably need to install it first using `pip`.


In [0]:
import torch
import torch.nn as nn

Alright, it worked.

Now, let's try to create a simple computational graph, as shown in the lecture, and in the tutorial http://colah.github.io/posts/2015-08-Backprop/.

The graph will be for the expression e=(a+b)*(b+1), with the values a=2 and b=1.

![caption](http://colah.github.io/posts/2015-08-Backprop/img/tree-eval.png =500x)

First, we need to create Pytorch tensors that hold a and b. Tensor is just a generalized matrix, with possibly more than two dimensions). Our a and b are simple scalars, which are simply one-dimensional tensors.

We also specify the requires_grad=True argument which tells Pytorch that we will later need the gradient of the tensors.



In [0]:
a = torch.tensor([2.],  requires_grad=True)
b = torch.tensor([1.],  requires_grad=True)

Now, let's create the intermediary tensors c and d, and the final tensor e. We can use regular Python operators to define them, using existing tensors:

In [0]:
c = a + b
d = b + 1
e = c * d
print(e)

tensor([6.], grad_fn=<MulBackward0>)


Alright, c is now a Pytorch tensor holding a value 6. But it's more than just a container for a scalar value. Calling e.backward() backpropagates the value all through the graph:

In [0]:
e = c * d  
e.backward()

Now, the grad attributes of a and b hold the computed gradient. The expected gradient values are shown here:

![](http://colah.github.io/posts/2015-08-Backprop/img/tree-backprop.png =500x)

In [0]:
print(a.grad)
print(b.grad)

tensor([2.])
tensor([5.])


Alright, we have computed the gradients of a and b and they match the expected values.

Next, follow the Pytorch tutorials:

  * https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html#sphx-glr-beginner-nlp-pytorch-tutorial-py
  * https://pytorch.org/tutorials/beginner/pytorch_with_examples.html